# Generated by Django 5.0.4 on 2024-05-08 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_form_organisation'),
        ('organisations', '0025_video_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
    ]
