# Generated by Django 5.0.4 on 2024-05-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_formresponserequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='filled_by_organisation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='visible_to_all',
            field=models.BooleanField(default=True),
        ),
    ]
