# Generated by Django 5.0.4 on 2024-05-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_form_filled_by_organisation_form_visible_to_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='visible_to_all',
            field=models.BooleanField(default=False),
        ),
    ]
