# Generated by Django 5.0.4 on 2024-08-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_alter_form_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='mentor_end_form',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='mentor_start_form',
            field=models.BooleanField(default=False),
        ),
    ]
