# Generated by Django 5.1.7 on 2025-03-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_alter_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='sign_up_form',
            field=models.BooleanField(default=False),
        ),
    ]
