# Generated by Django 5.1.7 on 2025-03-25 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_organisationformresponserequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponserequirement',
            name='assigned',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisationformresponserequirement',
            name='assigned',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
