# Generated by Django 5.1.7 on 2025-04-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0018_superform_superformregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superform',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
