# Generated by Django 5.1.7 on 2025-04-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0019_alter_superform_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
