# Generated by Django 5.1.7 on 2025-05-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0020_question_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
