# Generated by Django 5.0 on 2024-02-08 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0006_supplimentaryinforequirement'),
        ('volunteer', '0002_supplementaryinfo_supplementaryinfograntee'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplimentaryinforequirement',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.supplementaryinfo'),
        ),
        migrations.AddField(
            model_name='supplimentaryinforequirement',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.opportunity'),
        ),
    ]
