# Generated by Django 5.0.2 on 2024-03-16 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0008_registrationstatus_registration_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='status',
        ),
        migrations.RemoveField(
            model_name='registrationstatus',
            name='date',
        ),
        migrations.CreateModel(
            name='VolunteerRegistrationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('Opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.opportunity')),
            ],
        ),
    ]
