# Generated by Django 5.0.2 on 2024-03-16 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0010_registration_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerregistrationstatus',
            name='status',
        ),
        migrations.AddField(
            model_name='volunteerregistrationstatus',
            name='registration_status',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='opportunities.registrationstatus'),
            preserve_default=False,
        ),
    ]
