# Generated by Django 5.0.2 on 2024-03-27 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0012_remove_opportunity_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.opportunity')),
            ],
        ),
    ]
