# Generated by Django 5.0.2 on 2024-03-28 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0014_alter_location_latitude_alter_location_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.registration')),
            ],
        ),
    ]
