# Generated by Django 5.0.2 on 2024-03-28 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0015_registrationabsence'),
        ('volunteer', '0008_alter_volunteer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='volunteerregistrationstatus',
            name='Opportunity',
        ),
        migrations.AddField(
            model_name='registration',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='volunteer.volunteer'),
        ),
        migrations.AddField(
            model_name='volunteerregistrationstatus',
            name='Registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opportunities.registration'),
        ),
    ]
