# Generated by Django 5.0.2 on 2024-03-28 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0017_opportunity_active_alter_registration_volunteer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteerregistrationstatus',
            old_name='Registration',
            new_name='registration',
        ),
    ]
