# Generated by Django 5.0.2 on 2024-03-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0018_rename_registration_volunteerregistrationstatus_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
