# Generated by Django 5.0.2 on 2024-04-02 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0019_alter_location_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2024, 4, 2, 8, 42, 21, 36748, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2024, 4, 2, 8, 42, 28, 203182, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
