# Generated by Django 5.0.2 on 2024-04-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0021_alter_opportunity_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerregistrationstatus',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
