# Generated by Django 5.0.4 on 2024-05-06 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0024_alter_linkedtags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedtags',
            name='tag',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='opportunities.tag'),
        ),
    ]
