# Generated by Django 5.0.4 on 2024-05-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0027_location_latitude_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
