# Generated by Django 5.0.4 on 2024-05-07 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0028_image_thumbnail_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'verbose_name_plural': 'Opportunities'},
        ),
        migrations.AlterModelOptions(
            name='registrationstatus',
            options={'verbose_name_plural': 'Registration Statuses'},
        ),
        migrations.AlterModelOptions(
            name='volunteerregistrationstatus',
            options={'verbose_name_plural': 'Volunteer Registration Statuses'},
        ),
    ]
