# Generated by Django 5.0.4 on 2024-05-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0029_alter_opportunity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
