# Generated by Django 5.0.4 on 2024-05-10 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0030_video_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedtags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.tag'),
        ),
        migrations.AddConstraint(
            model_name='linkedtags',
            constraint=models.UniqueConstraint(fields=('opportunity', 'tag'), name='unique_opportunity_tag'),
        ),
    ]
