# Generated by Django 5.0.4 on 2024-05-10 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0031_alter_linkedtags_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='icons/')),
                ('name', models.CharField(max_length=200)),
                ('invert', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='benefit',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='opportunities.icon'),
        ),
    ]
