# Generated by Django 5.0.4 on 2024-05-10 13:52

import opportunities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0032_icon_benefit_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='hex_colour',
            field=models.CharField(default=opportunities.models.generate_random_pastel_hex, max_length=7),
        ),
    ]
