# Generated by Django 5.0.4 on 2024-05-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0035_tag_hex_colour_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='hex_colour_to',
            field=models.CharField(max_length=7),
        ),
    ]
