# Generated by Django 5.0.4 on 2024-05-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0036_alter_tag_hex_colour_to'),
        ('volunteer', '0009_supplementaryinfo_organisation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='supplimentaryinforequirement',
            constraint=models.UniqueConstraint(fields=('opportunity', 'info'), name='unique_opportunity_info'),
        ),
    ]
