# Generated by Django 5.0.4 on 2024-05-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0037_supplimentaryinforequirement_unique_opportunity_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
