# Generated by Django 5.0.4 on 2024-08-04 16:41

import django.db.models.deletion
import opportunities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0039_alter_benefit_icon_alter_location_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=opportunities.models.get_random_filename_image),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to=opportunities.models.get_random_filename_image),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to=opportunities.models.get_random_filename_video),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=opportunities.models.get_random_filename_video),
        ),
        migrations.CreateModel(
            name='OpportunitySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=2000)),
                ('order', models.IntegerField()),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.opportunity')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
