# Generated by Django 5.0.4 on 2024-08-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0040_alter_image_image_alter_image_thumbnail_image_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='opportunitysection',
            constraint=models.UniqueConstraint(fields=('opportunity', 'order'), name='unique_order_opportunity'),
        ),
    ]
