# Generated by Django 5.0.4 on 2024-08-04 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0041_opportunitysection_unique_order_opportunity'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='opportunitysection',
            name='unique_order_opportunity',
        ),
    ]
