# Generated by Django 5.0.6 on 2024-08-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0042_remove_opportunitysection_unique_order_opportunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
