# Generated by Django 5.0.4 on 2024-08-22 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0043_alter_opportunity_name'),
        ('organisations', '0029_alter_image_image_alter_image_thumbnail_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='orgnaisation',
            field=models.ForeignKey(default=1005, on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OpportunityBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.benefit')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.opportunity')),
            ],
        ),
    ]
