# Generated by Django 5.0.4 on 2024-08-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0044_benefit_orgnaisation_opportunitybenefit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benefit',
            old_name='orgnaisation',
            new_name='organisation',
        ),
    ]
