# Generated by Django 5.0.4 on 2024-08-22 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0045_rename_orgnaisation_benefit_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opportunities.opportunity'),
        ),
    ]
