# Generated by Django 5.1.7 on 2025-04-16 15:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0019_alter_superform_description'),
        ('opportunities', '0046_alter_benefit_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 16, 15, 57, 38, 196026, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.form'),
        ),
    ]
