# Generated by Django 5.2.4 on 2025-07-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0047_opportunity_date_created_opportunity_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='rota_config',
            field=models.CharField(choices=[('SHARED', 'Shared Schedule'), ('PER_ROTA', 'Per Rota')], default='SHARED', max_length=50),
        ),
    ]
