# Generated by Django 5.2.4 on 2025-07-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0048_opportunity_rota_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='rota_config',
            field=models.CharField(choices=[('SHARED', 'Shared Schedule'), ('PER_ROLE', 'Per Role')], default='SHARED', max_length=50),
        ),
    ]
