# Generated by Django 5.2.4 on 2025-09-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0049_alter_opportunity_rota_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='show_times_on_sign_up',
            field=models.BooleanField(default=True),
        ),
    ]
