# Generated by Django 5.2.4 on 2025-10-02 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0050_opportunity_show_times_on_sign_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='week_start',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
