# Generated by Django 5.0.4 on 2024-05-07 12:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_admin', '0001_initial'),
        ('organisations', '0024_alter_thematiccategory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrgnaisationAdmin',
            new_name='OrganisationAdmin',
        ),
    ]
