# Generated by Django 5.1.7 on 2025-03-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_admin', '0004_emaildraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildraft',
            name='email_target_recipients',
            field=models.CharField(choices=[('all', 'All users'), ('volunteers', 'Volunteers'), ('organisations', 'Organisations')], default='volunteers', max_length=20),
            preserve_default=False,
        ),
    ]
