# Generated by Django 5.1.7 on 2025-03-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_admin', '0008_alter_emaildraft_email_target_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildraft',
            name='email_target_recipients',
            field=models.CharField(choices=[('organisations', 'Organisations'), ('all', 'All users'), ('volunteers', 'Volunteers')], max_length=20),
        ),
    ]
