# Generated by Django 5.1.7 on 2025-03-28 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0046_alter_benefit_opportunity'),
        ('org_admin', '0009_alter_emaildraft_email_target_recipients'),
        ('organisations', '0032_organisationview'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildraft',
            name='opportunity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opportunities.opportunity'),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
        migrations.AlterField(
            model_name='emaildraft',
            name='email_target_recipients',
            field=models.CharField(choices=[('all_opp_volunteers', 'All opportunity volunteers'), ('all_org_volunteers', 'All organisation volunteers'), ('volunteers', 'Volunteers'), ('organisations', 'Organisations'), ('all', 'All users')], max_length=20),
        ),
    ]
