# Generated by Django 5.0.2 on 2024-02-20 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_volunteersupplementaryinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplementaryinfograntee',
            name='volunteer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='volunteer.volunteer'),
            preserve_default=False,
        ),
    ]
