# Generated by Django 5.0.2 on 2024-03-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_supplementaryinfograntee_volunteer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerconditions',
            name='name',
        ),
    ]
