# Generated by Django 5.0.4 on 2024-05-10 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0026_remove_link_description_remove_link_name'),
        ('volunteer', '0008_alter_volunteer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplementaryinfo',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
    ]
