# Generated by Django 5.0.4 on 2024-06-06 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_admin', '0002_rename_orgnaisationadmin_organisationadmin'),
        ('volunteer', '0009_supplementaryinfo_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='org_admin.organisationadmin')),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='volunteer.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='MentorNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('MentorRecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.mentorrecord')),
            ],
        ),
        migrations.CreateModel(
            name='MentorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.DurationField()),
                ('MentorRecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.mentorrecord')),
            ],
        ),
    ]
