# Generated by Django 5.0.4 on 2024-06-06 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_admin', '0002_rename_orgnaisationadmin_organisationadmin'),
        ('volunteer', '0012_mentorsession_session_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentornotes',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='org_admin.organisationadmin'),
        ),
    ]
