# Generated by Django 5.1.7 on 2025-04-08 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0019_volunteer_preferred_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerContactPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.BooleanField(default=True)),
                ('whatsapp', models.BooleanField(default=True)),
                ('phone', models.BooleanField(default=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.volunteer')),
            ],
        ),
    ]
