# Generated by Django 5.0.2 on 2024-03-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_chat_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='broadcast',
            field=models.BooleanField(default=False),
        ),
    ]
