# Generated by Django 5.0.4 on 2024-05-15 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_messageseen'),
        ('organisations', '0027_alter_location_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automated_messages', to='organisations.organisation', unique=True)),
            ],
        ),
    ]
