# Generated by Django 5.0.4 on 2024-05-15 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_automatedmessage'),
        ('organisations', '0027_alter_location_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='automated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='automatedmessage',
            name='organisation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
    ]
