# Generated by Django 5.0.6 on 2024-09-05 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0007_remove_chat_automated_message_automated'),
        ('organisations', '0031_organisationsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chip_in_admins_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='organisations.organisation'),
        ),
    ]
