# Generated by Django 5.2.4 on 2025-07-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='schedule',
            name='recurrence_rule',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='repeat_days',
        ),
    ]
