# Generated by Django 5.2.4 on 2025-07-23 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0047_opportunity_date_created_opportunity_form'),
        ('rota', '0002_alter_schedule_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rota.schedule'),
        ),
        migrations.CreateModel(
            name='OneOffDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.opportunity')),
            ],
        ),
        migrations.AddField(
            model_name='occurrence',
            name='one_off_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rota.oneoffdate'),
        ),
    ]
