# Generated by Django 5.2.4 on 2025-07-24 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0047_opportunity_date_created_opportunity_form'),
        ('rota', '0003_alter_occurrence_schedule_oneoffdate_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='volunteershift',
            unique_together={('opportunity', 'occurrence')},
        ),
        migrations.CreateModel(
            name='VolunteerOneOffDateAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_off_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rota.oneoffdate')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.registration')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerRoleIntrest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.registration')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rota.role')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerScheduleAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.registration')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rota.schedule')),
            ],
        ),
        migrations.DeleteModel(
            name='VolunteerAvailability',
        ),
    ]
