# Generated by Django 5.2.4 on 2025-07-24 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0047_opportunity_date_created_opportunity_form'),
        ('rota', '0004_alter_volunteershift_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteershift',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='volunteershift',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opportunities.registration'),
        ),
    ]
