# Generated by Django 5.2.4 on 2025-07-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0047_opportunity_date_created_opportunity_form'),
        ('rota', '0005_remove_volunteershift_volunteer_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='volunteershift',
            unique_together={('registration', 'occurrence')},
        ),
        migrations.AddField(
            model_name='volunteershift',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='volunteershift',
            name='opportunity',
        ),
    ]
