# Generated by Django 5.2.4 on 2025-07-30 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0006_alter_volunteershift_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oneoffdate',
            name='role',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rota.role'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='one_off_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rota.oneoffdate', unique=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rota.schedule', unique=True),
        ),
        migrations.AlterField(
            model_name='volunteershift',
            name='rsvp_response',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('-', 'No Response')], default='-', max_length=10),
        ),
    ]
