# Generated by Django 5.2.4 on 2025-08-11 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0049_alter_opportunity_rota_config'),
        ('organisations', '0032_organisationview'),
        ('rota', '0007_oneoffdate_role_alter_occurrence_one_off_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteershift',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteershift',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('all_org', 'All Organisation Shifts'), ('all_opportunity', 'All Shifts for given Opportunities'), ('all_role', 'All shift for given roles'), ('specific_shifts', 'Specific shifts')], default='specific_shifts', max_length=20)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
                ('supervisor_opportunities', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='opportunities.opportunity')),
                ('supervisor_roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rota.role')),
                ('supervisor_shifts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rota.occurrence')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
