# Generated by Django 5.2.4 on 2025-08-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0049_alter_opportunity_rota_config'),
        ('rota', '0008_volunteershift_check_in_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='supervisor_opportunities',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='supervisor_roles',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='supervisor_shifts',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='supervisor_opportunities',
            field=models.ManyToManyField(blank=True, to='opportunities.opportunity'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='supervisor_roles',
            field=models.ManyToManyField(to='rota.role'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='supervisor_shifts',
            field=models.ManyToManyField(to='rota.occurrence'),
        ),
    ]
