# Generated by Django 5.2.4 on 2025-08-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0009_remove_supervisor_supervisor_opportunities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='volunteershift',
            name='rsvp_response',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('cmi', "Can't make it"), ('-', 'No Response')], default='-', max_length=10),
        ),
    ]
