# Generated by Django 5.2.4 on 2025-08-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0010_alter_role_description_alter_section_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='volunteer_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
