# Generated by Django 5.2.4 on 2025-08-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0011_role_volunteer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteershift',
            name='rsvp_reason',
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
    ]
