# Generated by Django 5.2.4 on 2025-08-23 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0032_organisationview'),
        ('rota', '0012_volunteershift_rsvp_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='supervisor_roles',
            field=models.ManyToManyField(blank=True, to='rota.role'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='supervisor_shifts',
            field=models.ManyToManyField(blank=True, to='rota.occurrence'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='supervisor',
            unique_together={('user', 'organisation')},
        ),
    ]
