# Generated by Django 5.2.4 on 2025-08-29 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0013_alter_supervisor_organisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneoffdate',
            name='role',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rota.role'),
        ),
    ]
