# Generated by Django 5.2.4 on 2025-10-02 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0014_alter_oneoffdate_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='week_start',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
