# Generated by Django 5.0 on 2023-12-08 14:34

import djrichtextfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_rename_links_link_rename_videos_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
