# Generated by Django 5.0 on 2023-12-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='thematicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_colour', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='thematic/')),
            ],
        ),
    ]
