# Generated by Django 5.0 on 2023-12-27 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_thematiccategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='organisationnThematicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.thematiccategory')),
            ],
        ),
    ]
