# Generated by Django 5.0 on 2024-01-12 15:26

import django.db.models.deletion
import djrichtextfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_organisationnthematiclink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='location',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', djrichtextfield.models.RichTextField()),
                ('first_line', models.CharField(max_length=200)),
                ('second_line', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
            ],
        ),
    ]
