# Generated by Django 5.0 on 2024-01-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0008_remove_organisation_location_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
