# Generated by Django 5.0 on 2024-02-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0009_organisation_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
