# Generated by Django 5.0 on 2024-02-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0010_alter_link_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
