# Generated by Django 5.0 on 2024-02-09 16:31

import djrichtextfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0011_alter_link_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
    ]
