# Generated by Django 5.0.2 on 2024-03-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0016_linktype_rename_link_link_url_remove_link_icon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='type',
            new_name='link_type',
        ),
        migrations.AddField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
