# Generated by Django 5.0.4 on 2024-05-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0017_rename_type_link_link_type_organisation_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
