# Generated by Django 5.0.4 on 2024-05-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0018_link_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linktype',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
