# Generated by Django 5.0.4 on 2024-05-06 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0020_remove_location_city_remove_location_first_line_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='description',
            new_name='address',
        ),
    ]
