# Generated by Django 5.0.4 on 2024-05-07 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0023_image_thumbnail_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thematiccategory',
            options={'verbose_name_plural': 'Thematic Categories'},
        ),
    ]
