# Generated by Django 5.0.6 on 2024-08-12 16:12

import organisations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0028_badge_badgeopporunity_volunteerbadge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=organisations.models.get_random_filename_image),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to=organisations.models.get_random_filename_image),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to=organisations.models.get_random_filename_video),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=organisations.models.get_random_filename_video),
        ),
    ]
