# Generated by Django 5.0.4 on 2024-09-04 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0029_alter_image_image_alter_image_thumbnail_image_and_more'),
        ('volunteer', '0017_alter_volunteer_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_interest', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.volunteer')),
            ],
            options={
                'unique_together': {('volunteer', 'organisation')},
            },
        ),
    ]
